apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
  pgdata.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --host=localhost --username=${POSTGRES_USER} --dbname=postgres <<-EOSQL
        CREATE TABLE test (id int, name text);
        INSERT INTO test (id, name) VALUES (1, 'one'), (2, 'two');
    EOSQL
