namespace NodeJS {
  interface ProcessEnv {
    REACT_APP_BACKEND_URI: string
    REACT_APP_FRONT_URI: string
    REACT_APP_BACKEND_PATH_LOGIN: string
    REACT_APP_BACKEND_PATH_LOGIN_INFO: string
    REACT_APP_BACKEND_PATH_LOGOUT: string
    REACT_APP_BACKEND_PATH_SIGNUP: string
    REACT_APP_BACKEND_PATH_VERIFY: string
    REACT_APP_BACKEND_PATH_RECOVERY: string
    REACT_APP_BACKEND_PATH_NEW_PASSWORD: string
    REACT_APP_BACKEND_EXPORT_DATAMARTS: string
    REACT_APP_BACKEND_EXPORT_SOURCES: string
    REACT_APP_BACKEND_EXPORT_DOWNLOAD: string
    REACT_APP_BACKEND_EXPORT_JOBS: string
  }
}
