const Joi = require('@hapi/joi');

/*
"chartConfiguration": {
    "chartType": "line",
    "fields": {
        "x": "created_month",
        "y": "package_count",
        "split": "keyword",
        "xFacet": "",
        "yFacet": "keyword",
        "trendline": "true"
    }
}
*/

const schema = Joi.object({
  _id: Joi.string().optional(), // generated by nedb
  name: Joi.string().required(),
  tags: Joi.array()
    .items(Joi.string().empty(''))
    .sparse()
    .optional(),
  connectionId: Joi.string()
    .optional()
    .empty(''),
  queryText: Joi.string()
    .optional()
    .empty(''),
  chartConfiguration: Joi.object({
    chartType: Joi.string()
      .optional()
      .empty(''),
    // key value pairings. key=chart property, value=field mapped to property
    fields: Joi.object()
      .unknown(true)
      .optional()
  }).optional(),
  createdDate: Joi.date().default(Date.now),
  modifiedDate: Joi.date().default(Date.now),
  createdBy: Joi.string().required(),
  modifiedBy: Joi.string().required(),
  lastAccessDate: Joi.date().default(Date.now)
});

function makeQueries(nedb) {
  function findOneById(id) {
    return nedb.queries.findOne({ _id: id });
  }

  function findAll() {
    return nedb.queries.find({});
  }

  function findByFilter(filter) {
    return nedb.queries.find(filter);
  }

  function removeById(id) {
    return nedb.queries.remove({ _id: id });
  }

  /**
   * Save query object
   * returns saved query object
   * @param {object} query
   */
  async function save(query) {
    query.modifiedDate = new Date();
    query.lastAccessDate = new Date();

    // clean tags if present
    // sqlpad v1 saved a lot of bad inputs
    if (Array.isArray(query.tags)) {
      query.tags = query.tags
        .filter(tag => {
          return typeof tag === 'string' && tag.trim() !== '';
        })
        .map(tag => {
          return tag.trim();
        });
    }
    const joiResult = schema.validate(query);
    if (joiResult.error) {
      return Promise.reject(joiResult.error);
    }
    if (query._id) {
      await nedb.queries.update({ _id: query._id }, joiResult.value, {
        upsert: true
      });
      return findOneById(query._id);
    }
    const newQuery = await nedb.queries.insert(joiResult.value);
    return newQuery;
  }

  return {
    findOneById,
    findAll,
    findByFilter,
    removeById,
    save
  };
}

module.exports = makeQueries;
